In [4]:
import numpy as np

features = np.array([[1,2],[3,4],[5,6]])
print(features)
# Number of records and input units
n_records, n_inputs = features.shape
# Number of hidden units
n_hidden = 2
weights_input_to_hidden = np.random.normal(0, n_inputs**-0.5, size=(n_inputs, n_hidden))


[[1 2]
 [3 4]
 [5 6]]


In [9]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(1, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(1, scale=0.1, size=(N_hidden, N_output))

print(weights_input_to_hidden)

# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

[[0.97658466 0.9765863  1.15792128]
 [1.07674347 0.95305256 1.054256  ]
 [0.95365823 0.95342702 1.02419623]
 [0.80867198 0.82750822 0.94377125]]
Hidden-layer Output:
[0.89894104 0.90301252 0.92622805]
Output-layer Output:
[0.93648699 0.93137376]
